xelatex hpmor-1.tex
xelatex hpmor-2.tex
xelatex hpmor-3.tex
xelatex hpmor-4.tex
xelatex hpmor-5.tex
xelatex hpmor-6.tex
xelatex hpmor-1.tex
xelatex hpmor-2.tex
xelatex hpmor-3.tex
xelatex hpmor-4.tex
xelatex hpmor-5.tex
xelatex hpmor-6.tex